### ISSUE TITLE
mkdir: cannot create directory ‘/bitnami/postgresql/conf’: Permission denied

### ISSUE THREAD

**Issue by walterEri** [bitnami/bitnami-docker-postgresql-repmgr#10]
I am deploying postgresql-ha using helm in a **openshift** environment.

I get the error:
- mkdir: cannot create directory ‘/bitnami/postgresql/conf’: Permission denied

```
postgresql-repmgr 07:15:56.34 Welcome to the Bitnami postgresql-repmgr container
--
  | postgresql-repmgr 07:15:56.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
  | postgresql-repmgr 07:15:56.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
  | postgresql-repmgr 07:15:56.34 Send us your feedback at containers@bitnami.com
  | postgresql-repmgr 07:15:56.34
  | postgresql-repmgr 07:15:56.37 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
  | repmgr 07:15:56.43 INFO  ==> Validating settings in REPMGR_* env vars...
  | postgresql 07:15:56.44 INFO  ==> Validating settings in POSTGRESQL_* env vars..
  | repmgr 07:15:56.44 INFO  ==> Querying all partner nodes for common upstream node...
  | repmgr 07:15:56.57 INFO  ==> There are no nodes with primary role. Assuming the primary role...
  | repmgr 07:15:56.57 INFO  ==> Preparing PostgreSQL configuration...
  | mkdir: cannot create directory ‘/bitnami/postgresql/conf’: Permission denied
  | postgresql 07:15:56.58 INFO  ==> Stopping PostgreSQL...
```

**Comment by juan131** [comment]
Hi @walterEri 

Could you please share the **values.yaml** you're using to deploy PostgreSQL HA in Openshift? 

By default this chart uses a "SecurityContext" to adapt the permissions of the volume attatched to the PostgreSQL container so the user running the container has writing permissions on it. See

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L38

Do you know if your K8s cluster has support for this feature?

**Comment by walterEri** [comment]
I am using values-production.yaml file
[values-production.txt](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/files/4152477/values-production.txt)

**Comment by walterEri** [comment]
I have fixed **Permission denied issue** by running below command on the node hostpath

```
sudo chown -R 1001:1001 <volumepath>
```

**Comment by swapnilpotnis** [comment]
@juan131 : I am facing the same issue for "dependency-track" helm chart having dependency over bitnami-postgresql

`postgresql 00:02:13.90 WARN  ==> Data directory is set with a legacy value, adapting POSTGRESQL_DATA_DIR...
postgresql 00:02:13.91 WARN  ==> POSTGRESQL_DATA_DIR set to "/bitnami/postgresql/data"!!
postgresql 00:02:13.92 
postgresql 00:02:13.92 Welcome to the Bitnami postgresql container
postgresql 00:02:13.93 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 00:02:13.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 00:02:13.93 Send us your feedback at containers@bitnami.com
postgresql 00:02:13.93 
postgresql 00:02:13.94 INFO  ==> ** Starting PostgreSQL setup **
postgresql 00:02:13.99 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 00:02:14.00 INFO  ==> Loading custom pre-init scripts...
postgresql 00:02:14.00 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql’: Permission denied
postgresql 00:02:14.01 INFO  ==> Stopping PostgreSQL..`

I tried @walterEri's solution but that didnt seem to resolve my issue. Any clue what could be done to further debug the issue??

**Comment by juan131** [comment]
Hi @swapnilpotnis 

What chart are you using that uses Bitnami one as dependency? The error below suggests me that the chart is using an old version of PostgreSQL and it should update its requirements.

```console
postgresql 00:02:13.90 WARN ==> Data directory is set with a legacy value, adapting POSTGRESQL_DATA_DIR... postgresql 00:02:13.91 WARN ==> POSTGRESQL_DATA_DIR set to "/bitnami/postgresql/data"!! postgresql 00:02:13.92
```

The current latest version for PostgreSQL is 9.3.3:

```console
$ helm search repo bitnami/postgresql
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/postgresql   	9.3.3        	11.9.0     	Chart for PostgreSQL, an object-relational data...
```

**Comment by swapnilpotnis** [comment]
@juan131 : Dependency Track(https://hub.helm.sh/charts/tietoevryfs/dependency-track) is the one using bitnami/postgresql.

I tried updating the version of bitnami to the latest version but still the same error perists

`    Container ID:   docker://cd14a1cda7c73d54a1c3da16a020e1f95b832dc2d5e15c7201616c3fa565ce3b
    Image:          docker.io/bitnami/postgresql:latest
    Image ID:       docker-pullable://bitnami/postgresql@sha256:bef73303401c0149c9409a631450afb0d1105a453aab4ba6ef937e6e6d9716ed
`

Error:
`postgresql 07:56:52.84 Welcome to the Bitnami postgresql container
postgresql 07:56:52.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 07:56:52.84 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 07:56:52.84 
postgresql 07:56:52.86 INFO  ==> ** Starting PostgreSQL setup **
postgresql 07:56:52.87 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 07:56:52.88 INFO  ==> Loading custom pre-init scripts...
postgresql 07:56:52.88 INFO  ==> Initializing PostgreSQL database...
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 07:56:52.90 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 07:56:52.90 WARN  ==> Lack of permissions on data directory!
postgresql 07:56:52.91 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 07:56:52.91 INFO  ==> Generating local authentication configuration
ls: cannot open directory '/bitnami/postgresql/data': Permission denied
postgresql 07:56:52.93 INFO  ==> Stopping PostgreSQL..`

**Comment by juan131** [comment]
Hi @swapnilpotnis 

Thanks!! As you can see in the [requirements.yaml](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/requirements.yaml), it's using the Bitnami PostgreSQL chart version **8.10**.

You can see there's a major version of PostgreSQL (9.x.x) already published on our side:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql/Chart.yaml

Anyway, I gave it a try and I found no issues (I'm using a GKE cluster):

```console
$ helm repo add evryfs-oss https://evryfs.github.io/helm-charts/
$ kubectl create ns dependency-track
$ helm install dependency-track evryfs-oss/dependency-track --namespace dependency-track
$ kubectl get pods -n dependency-track
NAME                               READY   STATUS    RESTARTS   AGE
dependency-track-5d6f7c4f6-98cjr   1/1     Running   0          118s
dependency-track-postgresql-0      1/1     Running   0          118s
$ kubectl logs -n dependency-track dependency-track-postgresql-0
postgresql 06:33:16.40
postgresql 06:33:16.40 Welcome to the Bitnami postgresql container
postgresql 06:33:16.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 06:33:16.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 06:33:16.40
postgresql 06:33:16.43 INFO  ==> ** Starting PostgreSQL setup **
postgresql 06:33:16.46 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 06:33:16.47 INFO  ==> Loading custom pre-init scripts...
postgresql 06:33:16.48 INFO  ==> Initializing PostgreSQL database...
postgresql 06:33:16.51 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 06:33:16.52 INFO  ==> Generating local authentication configuration
postgresql 06:33:18.15 INFO  ==> Starting PostgreSQL in background...
postgresql 06:33:18.56 INFO  ==> Creating user deptrack
postgresql 06:33:18.58 INFO  ==> Granting access to "deptrack" to the database "deptrack"
postgresql 06:33:18.60 INFO  ==> Configuring replication parameters
postgresql 06:33:18.62 INFO  ==> Configuring fsync
postgresql 06:33:18.63 INFO  ==> Loading custom scripts...
postgresql 06:33:18.64 INFO  ==> Enabling remote connections
postgresql 06:33:18.65 INFO  ==> Stopping PostgreSQL...
postgresql 06:33:19.66 INFO  ==> ** PostgreSQL setup finished! **

postgresql 06:33:19.68 INFO  ==> ** Starting PostgreSQL **
2020-09-01 06:33:19.700 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-09-01 06:33:19.700 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-09-01 06:33:19.705 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-09-01 06:33:19.727 GMT [114] LOG:  database system was shut down at 2020-09-01 06:33:18 GMT
2020-09-01 06:33:19.734 GMT [1] LOG:  database system is ready to accept connections
```

What kind of K8s cluster are you using?
What kind of persistent volumes does your K8s cluster provides?

**Comment by swapnilpotnis** [comment]
@juan131 : Appreciate your efforts of going and installing D.T just to check the issue.

I am using an On-Prem K8s cluster where I myself am creating the required set of PV which could be further Claimed by D.T along with Postgresql

**Comment by juan131** [comment]
Hi @swapnilpotnis 

I think the issue could be related with those PV you're creating... Some issue while applying the SecurityContext to adapt them... Could you try enabling the initContainer to adapt them? You just need to ensure the parameter `volumePermissions.enabled` is set to `true`. More information in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#adjust-permissions-of-persistent-volume-mountpoint
